package com.example.muslimvn.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Bảng màu Monochrome / Trắng Đen chuẩn Material 3 của Google.
 * Không sử dụng sắc màu thương hiệu (hue/chroma) cấp hệ thống app
 * để mang lại giao diện tối giản, trung tính và dễ chịu cho mọi người dùng.
 */

// Light scheme (Sáng - Trắng Đen)
val md_light_primary = Color(0xFF000000)
val md_light_on_primary = Color(0xFFFFFFFF)
val md_light_primary_container = Color(0xFFE0E0E0)
val md_light_on_primary_container = Color(0xFF1A1A1A)
val md_light_secondary = Color(0xFF5E5E5E)
val md_light_on_secondary = Color(0xFFFFFFFF)
val md_light_secondary_container = Color(0xFFE7E7E7)
val md_light_on_secondary_container = Color(0xFF1F1F1F)
val md_light_tertiary = Color(0xFF4F4F4F)
val md_light_on_tertiary = Color(0xFFFFFFFF)
val md_light_tertiary_container = Color(0xFFEDEDED)
val md_light_on_tertiary_container = Color(0xFF212121)
val md_light_error = Color(0xFFBA1A1A)
val md_light_on_error = Color(0xFFFFFFFF)
val md_light_error_container = Color(0xFFFFDAD6)
val md_light_on_error_container = Color(0xFF410002)

val md_light_background = Color(0xFFFFFFFF)
val md_light_on_background = Color(0xFF1A1A1A)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_on_surface = Color(0xFF1A1A1A)
val md_light_surface_variant = Color(0xFFE6E6E6)
val md_light_on_surface_variant = Color(0xFF474747)
val md_light_outline = Color(0xFF757575)
val md_light_outline_variant = Color(0xFFC2C2C2)
val md_light_inverse_surface = Color(0xFF303030)
val md_light_inverse_on_surface = Color(0xFFF2F2F2)
val md_light_inverse_primary = Color(0xFFFFFFFF)

val md_light_surface_dim = Color(0xFFD8D8D8)
val md_light_surface_bright = Color(0xFFFFFFFF)
val md_light_surface_container_lowest = Color(0xFFFFFFFF)
val md_light_surface_container_low = Color(0xFFF7F7F7)
val md_light_surface_container = Color(0xFFF2F2F2)
val md_light_surface_container_high = Color(0xFFECECEC)
val md_light_surface_container_highest = Color(0xFFE0E0E0)

// Dark scheme (Tối - Đen Trắng)
val md_dark_primary = Color(0xFFFFFFFF)
val md_dark_on_primary = Color(0xFF000000)
val md_dark_primary_container = Color(0xFF3A3A3A)
val md_dark_on_primary_container = Color(0xFFE6E6E6)
val md_dark_secondary = Color(0xFFC9C9C9)
val md_dark_on_secondary = Color(0xFF303030)
val md_dark_secondary_container = Color(0xFF474747)
val md_dark_on_secondary_container = Color(0xFFE6E6E6)
val md_dark_tertiary = Color(0xFFD7D7D7)
val md_dark_on_tertiary = Color(0xFF303030)
val md_dark_tertiary_container = Color(0xFF4A4A4A)
val md_dark_on_tertiary_container = Color(0xFFEDEDED)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_on_error = Color(0xFF690005)
val md_dark_error_container = Color(0xFF93000A)
val md_dark_on_error_container = Color(0xFFFFDAD6)

val md_dark_background = Color(0xFF000000)
val md_dark_on_background = Color(0xFFE6E6E6)
val md_dark_surface = Color(0xFF000000)
val md_dark_on_surface = Color(0xFFE6E6E6)
val md_dark_surface_variant = Color(0xFF303030)
val md_dark_on_surface_variant = Color(0xFFC2C2C2)
val md_dark_outline = Color(0xFF8E8E8E)
val md_dark_outline_variant = Color(0xFF474747)
val md_dark_inverse_surface = Color(0xFFE6E6E6)
val md_dark_inverse_on_surface = Color(0xFF1F1F1F)
val md_dark_inverse_primary = Color(0xFF000000)

val md_dark_surface_dim = Color(0xFF121212)
val md_dark_surface_bright = Color(0xFF3A3A3A)
val md_dark_surface_container_lowest = Color(0xFF0A0A0A)
val md_dark_surface_container_low = Color(0xFF141414)
val md_dark_surface_container = Color(0xFF1E1E1E)
val md_dark_surface_container_high = Color(0xFF282828)
val md_dark_surface_container_highest = Color(0xFF333333)

// Semantic colors (Success) trung tính theo theme
val md_light_success = Color(0xFF000000)
val md_light_on_success = Color(0xFFFFFFFF)
val md_light_success_container = Color(0xFFE0E0E0)
val md_light_on_success_container = Color(0xFF1A1A1A)

val md_dark_success = Color(0xFFFFFFFF)
val md_dark_on_success = Color(0xFF000000)
val md_dark_success_container = Color(0xFF3A3A3A)
val md_dark_on_success_container = Color(0xFFE6E6E6)
