package com.example.muslimvn.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Bảng màu MuslimVN - Giữ nền tối giản Trắng Đen trung tính, kết hợp điểm nhấn
 * thương hiệu Xanh Ngọc (#055136) ở các thành phần tương tác chính (nút, icon active, tab, badge).
 */

val BrandGreen = Color(0xFF055136)
val BrandGreenLight = Color(0xFF108A5B)
val BrandGreenContainerLight = Color(0xFFD3E8DD)
val BrandGreenContainerDark = Color(0xFF055136)

// Light scheme (Nền Sáng Trắng/Xám - Điểm nhấn Xanh Ngọc #055136 cho tương tác)
val md_light_primary = Color(0xFF055136)
val md_light_on_primary = Color(0xFFFFFFFF)
val md_light_primary_container = Color(0xFFD3E8DD)
val md_light_on_primary_container = Color(0xFF1A1A1A)
val md_light_secondary = Color(0xFF055136)
val md_light_on_secondary = Color(0xFFFFFFFF)
val md_light_secondary_container = Color(0xFFE4F1E9)
val md_light_on_secondary_container = Color(0xFF1A1A1A)
val md_light_tertiary = Color(0xFF2C6852)
val md_light_on_tertiary = Color(0xFFFFFFFF)
val md_light_tertiary_container = Color(0xFFD8ECE2)
val md_light_on_tertiary_container = Color(0xFF1A1A1A)
val md_light_error = Color(0xFFBA1A1A)
val md_light_on_error = Color(0xFFFFFFFF)
val md_light_error_container = Color(0xFFFFDAD6)
val md_light_on_error_container = Color(0xFF410002)

val md_light_background = Color(0xFFFFFFFF)
val md_light_on_background = Color(0xFF1A1A1A)
val md_light_surface = Color(0xFFFFFFFF)
val md_light_on_surface = Color(0xFF1A1A1A)
val md_light_surface_variant = Color(0xFFE6E6E6)
val md_light_on_surface_variant = Color(0xFF474747)
val md_light_outline = Color(0xFF757575)
val md_light_outline_variant = Color(0xFFC2C2C2)
val md_light_inverse_surface = Color(0xFF303030)
val md_light_inverse_on_surface = Color(0xFFF2F2F2)
val md_light_inverse_primary = Color(0xFF62D2A2)

val md_light_surface_dim = Color(0xFFD8D8D8)
val md_light_surface_bright = Color(0xFFFFFFFF)
val md_light_surface_container_lowest = Color(0xFFFFFFFF)
val md_light_surface_container_low = Color(0xFFF7F7F7)
val md_light_surface_container = Color(0xFFF2F2F2)
val md_light_surface_container_high = Color(0xFFECECEC)
val md_light_surface_container_highest = Color(0xFFE0E0E0)

// Dark scheme (Nền Tối Đen - Điểm nhấn Xanh Ngọc dịu mắt cho tương tác)
val md_dark_primary = Color(0xFF2D9668)
val md_dark_on_primary = Color(0xFF002918)
val md_dark_primary_container = Color(0xFF055136)
val md_dark_on_primary_container = Color(0xFFE6E6E6)
val md_dark_secondary = Color(0xFF247D56)
val md_dark_on_secondary = Color(0xFF002918)
val md_dark_secondary_container = Color(0xFF083B25)
val md_dark_on_secondary_container = Color(0xFFE6E6E6)
val md_dark_tertiary = Color(0xFF338E6A)
val md_dark_on_tertiary = Color(0xFF002918)
val md_dark_tertiary_container = Color(0xFF0D3A28)
val md_dark_on_tertiary_container = Color(0xFFE6E6E6)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_on_error = Color(0xFF690005)
val md_dark_error_container = Color(0xFF93000A)
val md_dark_on_error_container = Color(0xFFFFDAD6)

val md_dark_background = Color(0xFF0B1014)
val md_dark_on_background = Color(0xFFE6E6E6)
val md_dark_surface = Color(0xFF0B1014)
val md_dark_on_surface = Color(0xFFE6E6E6)
val md_dark_surface_variant = Color(0xFF1C2835)
val md_dark_on_surface_variant = Color(0xFFC2C2C2)
val md_dark_outline = Color(0xFF6B7D8D)
val md_dark_outline_variant = Color(0xFF263545)
val md_dark_inverse_surface = Color(0xFFE6E6E6)
val md_dark_inverse_on_surface = Color(0xFF1F1F1F)
val md_dark_inverse_primary = Color(0xFF055136)

val md_dark_surface_dim = Color(0xFF0B1014)
val md_dark_surface_bright = Color(0xFF283646)
val md_dark_surface_container_lowest = Color(0xFF070B0E)
val md_dark_surface_container_low = Color(0xFF0E141A)
val md_dark_surface_container = Color(0xFF0B1014)
val md_dark_surface_container_high = Color(0xFF151E28)
val md_dark_surface_container_highest = Color(0xFF1C2835)

// Semantic colors (Success) với tông Xanh Ngọc thương hiệu
val md_light_success = Color(0xFF055136)
val md_light_on_success = Color(0xFFFFFFFF)
val md_light_success_container = Color(0xFFD3E8DD)
val md_light_on_success_container = Color(0xFF023222)

val md_dark_success = Color(0xFF2D9668)
val md_dark_on_success = Color(0xFF002918)
val md_dark_success_container = Color(0xFF055136)
val md_dark_on_success_container = Color(0xFFB2DFCA)

// Semantic colors (Warning)
val md_light_warning = Color(0xFF825500)
val md_light_on_warning = Color(0xFFFFFFFF)
val md_light_warning_container = Color(0xFFFFDDB3)
val md_light_on_warning_container = Color(0xFF2A1800)

val md_dark_warning = Color(0xFFFFB951)
val md_dark_on_warning = Color(0xFF452B00)
val md_dark_warning_container = Color(0xFF633F00)
val md_dark_on_warning_container = Color(0xFFFFDDB3)

// Semantic colors (Info)
val md_light_info = Color(0xFF0061A4)
val md_light_on_info = Color(0xFFFFFFFF)
val md_light_info_container = Color(0xFFD1E4FF)
val md_light_on_info_container = Color(0xFF001D36)

val md_dark_info = Color(0xFF9ECAFF)
val md_dark_on_info = Color(0xFF003258)
val md_dark_info_container = Color(0xFF00497D)
val md_dark_on_info_container = Color(0xFFD1E4FF)
